const tintColorLight = "#FF3E39";

export default {
  primary: "#FF3E39",
  light: {
    text: "#181818",
    background: "#FFFFFF",
    tint: tintColorLight,
    tabIconDefault: "#BDBDBD",
    tabIconSelected: "#181818",
    textHigh: "#181818",
    textMedium: "#363636",
    textLow: "#747474",
    textPlaceholder: "#A3A3A3",
    buttonActive: "#595959",
    buttonMuted: "#BDBDBD",
    colorPrimary: "#FF3E39",
    colorOn: "#FFFFFF",
    border: "#E5E5E5",
    surfaceOne: "#F3F3F3",
  },
  dark: {
    text: "#FFFFFF",
    background: "#181818",
    tint: tintColorLight,
    tabIconDefault: "#4F4F4F",
    tabIconSelected: "#FFFFFF",
    textHigh: "#FFFFFF",
    textMedium: "#E1E1E1",
    textLow: "#A3A3A3",
    textPlaceholder: "#747474",
    buttonActive: "#A3A3A3",
    buttonMuted: "#4F4F4F",
    colorPrimary: "#FF3E39",
    colorOn: "#FFFFFF",
    border: "#2B2B2B",
    surfaceOne: "#242424",
  },
};

const FONT = {
  button: {
    fontFamily: "InterBold",
    fontWeight: "700",
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.17,
  },
  caption: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0.13,
  },
  smallLabel: {
    fontFamily: "InterRegular",
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: -0,
  },
  setting: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  header: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  itemBody: {
    fontFamily: "NotoSerifRegular",
    fontWeight: "400",
    fontSize: 15,
    lineHeight: 25,
    letterSpacing: -0.225,
  },
  timestamp: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.14,
  },
  itemDesc: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.14,
  },
  itemDescTiny: {
    fontFamily: "InterRegular",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: -0.14,
  },
  itemTitle: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.17,
  },
  itemTitleCentered: {
    fontFamily: "InterBold",
    fontWeight: "700",
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.17,
  },
  pageTitle: {
    fontFamily: "InterBold",
    fontWeight: "700",
    fontSize: 34,
    lineHeight: 41,
    letterSpacing: -0.34,
  },
  navLinkRegular: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.17,
  },
  displayTitle: {
    fontFamily: "NotoSerifMedium",
    fontWeight: "500",
    fontSize: 29,
    lineHeight: 35,
    letterSpacing: -0.217,
  },
  inactiveItem: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  activeItem: {
    fontFamily: "InterBold",
    fontWeight: "700",
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  textInput: {
    fontFamily: "InterRegular",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0,
  },
  tabBarTitle: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: -0.1,
  },
  displaySubtitle: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 19,
    lineHeight: 24,
    letterSpacing: -0.19,
  },
  sectionTitle: {
    fontFamily: "InterBold",
    fontWeight: "700",
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.22,
  },
};
