const tintColorLight = "#FF3E39";

export default {
  light: {
    text: "#181818",
    background: "#FFFFFF",
    tint: tintColorLight,
    tabIconDefault: "#BDBDBD",
    tabIconSelected: "#181818",
    textHigh: "#181818",
    textMedium: "#363636",
    textLow: "#747474",
    textPlaceholder: "#A3A3A3",
    buttonActive: "#595959",
    buttonMuted: "#BDBDBD",
    colorPrimary: "#FF3E39",
    colorOn: "#FFFFFF",
    border: "#E5E5E5",
    surfaceOne: '#FCFCFC',
  },
  dark: {
    text: "#FFFFFF",
    background: "#181818",
    tint: tintColorLight,
    tabIconDefault: "#4F4F4F",
    tabIconSelected: "#FFFFFF",
    textHigh: "#FFFFFF",
    textMedium: "#E1E1E1",
    textLow: "#A3A3A3",
    textPlaceholder: "#747474",
    buttonActive: "#A3A3A3",
    buttonMuted: "#4F4F4F",
    colorPrimary: "#FF3E39",
    colorOn: "#FFFFFF",
    border: "#2B2B2B",
    surfaceOne: '#1B1B1B',
  },
};
